### ISSUE TITLE
PhyloSuite not working

### ISSUE THREAD

**Issue by Gwendoline998** [dongzhang0725/PhyloMAN#86]
Hi, 
I am a new user of PhyloSuite, I tried to download nucleotide sequences from NCBI, but it does not work. The pop-up window is: The search failed for some of the sequences. As this may have been caused by a network problem, you can wait for a while and try again.
If the problem persists you may report it at https://github.com/dongzhang0725/PhyloSuite/issues or send an email with the detailed traceback to dongzhang0725@gmail.com

thank you

**Comment by Gwendoline998** [comment]
Traceback (most recent call last):
  File "src\Lg_SerhNCBI.py", line 493, in search
  File "Bio\Entrez\__init__.py", line 234, in esearch
  File "Bio\Entrez\__init__.py", line 569, in _open
  File "urllib\request.py", line 223, in urlopen
  File "urllib\request.py", line 532, in open
  File "urllib\request.py", line 642, in http_response
  File "urllib\request.py", line 570, in error
  File "urllib\request.py", line 504, in _call_chain
  File "urllib\request.py", line 650, in http_error_default
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

**Comment by dongzhang0725** [comment]
Hi, the best way to resolve this is to copy the sequence IDs in NCBI's
search box in nucleotide database, then download the sequences and import
them to PhyloSuite.
see
http://phylosuite.jushengwu.com/dongzhang0725.github.io/PhyloSuite-demo/five_ways_to_import/

Gwendoline998 ***@***.***> 于2023年11月21日周二 18:12写道：
